#!/bin/bash

# hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

#install zsh
echo 'install oh-my-zhs'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

#global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

#symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

#symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

#symlink yarn prefs
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

#fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

echo 'install composer'
echo '----------------'
cd ~/.dotfiles
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
echo 'move composer to /usr/local/bin/composer'
mv -f composer.phar /usr/local/bin/composer

#activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'install wget'
echo '------------'
brew install wget --overwrite

echo 'install httpie'
echo '------------'
brew install httpie

echo 'install ncdu'
echo '------------'
brew install ncdu

echo 'install hub'
echo '-----------'
brew install hub

echo 'install ack'
echo '------------'
brew install ack

echo 'install doctl'
echo '-------------'
brew install doctl

echo 'install brew-cask'
echo '------------------'
brew tap caskroom/cask
brew install brew-cask

echo 'install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

echo 'install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

echo 'install php'
echo '------------'
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php72
brew install php72-xdebug
sudo brew services start homebrew/php/php72
brew install homebrew/php/php72-mcrypt
brew install homebrew/php/php72-imagick

echo 'install redis'
echo '------------'
brew install redis
brew install homebrew/php/php72-redis

echo 'install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'install mysql'
echo '---------------'
brew install mysql
brew services start mysql

echo 'install yarn'
echo '------------'
brew install yarn

echo 'install phpunit-watcher'
echo '---------------------'
composer global require spatie/phpunit-watcher

echo 'install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'install gulp'
echo '------------'
npm install -g gulp

echo 'install ghostscript'
echo '-------------------'
brew install ghostscript

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'all done'
echo 'Things to do to make the agnoster terminal theme work:'

#patch font contains right characters for promt
echo '1. install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf' 

#install solarized http://ethanschoonover.com/solarized
echo '2. install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. set some sensible os x defaults by running: $HOME/.dotfiles/osx/set-defaults.sh'
echo '2. make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
